---
title: "GA Customer Revenue Production"
author: "Nisha Dayananda"
date: "12/1/2018"
output: html_document
---

```{r}
#I have used train_preprocessed and test_preprocessed files for decision tree implementation.
#Read train and test files
setwd("/Users/nisha_dayanand/Desktop/ENPM808/Project/google-revenue-prediction/preprocessed")
train_df <- read.csv(file="train_preprocessed.csv")
test_df <- read.csv(file="test_preprocessed.csv")

head(train_df)
head(test_df)

```
```{r}
library(rpart)
library(rattle)
train_df$totals.transactionRevenue[is.na(train_df$totals.transactionRevenue)] <- 0
test_df$totals.transactionRevenue[is.na(test_df$totals.transactionRevenue)] <- 0
train_df$logRevenue <- log(train_df$totals.transactionRevenue + 1)
test_df$logRevenue <- log(test_df$totals.transactionRevenue + 1)
```

```{r}
#split the train data into train and test for validation 
set.seed(123) 
index <- sample(1:nrow(train_df),size = 0.8*nrow(train_df)) 
train <- train_df[index,]
test <- train_df[-index,]

```



```{r}
#decision tree implementation on split train data
rt <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            totals.sessionQualityDim + 
            totals.timeOnSite + 
            visit_hour +
            visitNumber + 
            trafficSource.referralPath + 
            geoNetwork.country + 
            geoNetwork.metro, data=train)

#applying the trained model on split test data
test.pred.rtree <- predict(rt,test)
RMSE.rtree <- sqrt(mean((test.pred.rtree-test$logRevenue)^2))
RMSE.rtree

RMSE <- function(m, o){
  sqrt(mean((m - o)^2))
}

#decision tree implementation on actual train data 
rt_0 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            totals.sessionQualityDim + 
            totals.timeOnSite + 
            visit_hour +
            visitNumber + 
            trafficSource.referralPath + 
            geoNetwork.country + 
            geoNetwork.metro, data=train_df)

#applying the trained model on actual test data
test_df.pred.rtree_0 <- predict(rt_0,test_df)
p <- as.data.frame(test_df.pred.rtree_0)
result_df <- data.frame(fullVisitorId=test_df$fullVisitorId, transactionRevenue=test_df$totals.totalTransactionRevenue, predictedRevenue=expm1(p$test_df.pred.rtree_0))
result_df <- aggregate(. ~ fullVisitorId, result_df, sum)
RMSE(log1p(result_df$transactionRevenue), log1p(result_df$predictedRevenue))
```
```{r}
# decision tree plot
fancyRpartPlot(rt_0)
```


```{r}
#decision tree implementation on split train data
rt1 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            totals.sessionQualityDim + 
            totals.timeOnSite, data=train)

#applying the trained model on split test data
test.pred.rtree1 <- predict(rt1,test)
RMSE.rtree1 <- sqrt(mean((test.pred.rtree1-test$logRevenue)^2))
RMSE.rtree1

#decision tree implementation on actual train data 
rt_1 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            totals.sessionQualityDim + 
            totals.timeOnSite, data=train_df)

#applying the trained model on actual test data
test_df.pred.rtree_1 <- predict(rt_1,test_df)
p1 <- as.data.frame(test_df.pred.rtree_1)
result_df1 <- data.frame(fullVisitorId=test_df$fullVisitorId, transactionRevenue=test_df$totals.totalTransactionRevenue, predictedRevenue=expm1(p1$test_df.pred.rtree_1))
result_df1 <- aggregate(. ~ fullVisitorId, result_df1, sum)
RMSE(log1p(result_df1$transactionRevenue), log1p(result_df1$predictedRevenue))
```
```{r}
# decision tree plot
fancyRpartPlot(rt_1)
```


```{r}
#decision tree implementation on split train data
rt2 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            totals.sessionQualityDim + 
            totals.timeOnSite + visit_hour, data=train)

#applying the trained model on split test data
test.pred.rtree2 <- predict(rt2,test)
RMSE.rtree2 <- sqrt(mean((test.pred.rtree2-test$logRevenue)^2))
RMSE.rtree2

#decision tree implementation on actual train data 
rt_2 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            totals.sessionQualityDim + 
            totals.timeOnSite + visit_hour, data=train_df)

#applying the trained model on actual test data
test_df.pred.rtree_2 <- predict(rt_1,test_df)
p2 <- as.data.frame(test_df.pred.rtree_2)
result_df2 <- data.frame(fullVisitorId=test_df$fullVisitorId, transactionRevenue=test_df$totals.totalTransactionRevenue, predictedRevenue=expm1(p2$test_df.pred.rtree_2))
result_df2 <- aggregate(. ~ fullVisitorId, result_df2, sum)
RMSE(log1p(result_df2$transactionRevenue), log1p(result_df2$predictedRevenue))
```
```{r}
# decision tree plot
fancyRpartPlot(rt_2)
```

```{r}
#decision tree implementation on split train data
rt3 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            geoNetwork.region, data=train)

#applying the trained model on split test data
test.pred.rtree3 <- predict(rt3,test)
RMSE.rtree3 <- sqrt(mean((test.pred.rtree3-test$logRevenue)^2))
RMSE.rtree3

#decision tree implementation on actual train data 
rt_3 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            geoNetwork.region, data=train_df)

#applying the trained model on actual test data
test_df.pred.rtree_3 <- predict(rt_1,test_df)
p3 <- as.data.frame(test_df.pred.rtree_3)
result_df3 <- data.frame(fullVisitorId=test_df$fullVisitorId, transactionRevenue=test_df$totals.totalTransactionRevenue, predictedRevenue=expm1(p3$test_df.pred.rtree_3))
result_df3 <- aggregate(. ~ fullVisitorId, result_df3, sum)
RMSE(log1p(result_df3$transactionRevenue), log1p(result_df3$predictedRevenue))
```

```{r}
# decision tree plot
fancyRpartPlot(rt_3)
```


```{r}
#decision tree implementation on split train data
rt4 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            geoNetwork.region + device.deviceCategory, data=train)
test.pred.rtree4 <- predict(rt4,test)
RMSE.rtree4 <- sqrt(mean((test.pred.rtree4-test$logRevenue)^2))
RMSE.rtree4

#decision tree implementation on actual train data 
rt_4 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            geoNetwork.region + device.deviceCategory, data=train_df)

#applying the trained model on actual test data
test_df.pred.rtree_4 <- predict(rt_4,test_df)
p4 <- as.data.frame(test_df.pred.rtree_4)
result_df4 <- data.frame(fullVisitorId=test_df$fullVisitorId, transactionRevenue=test_df$totals.totalTransactionRevenue, predictedRevenue=expm1(p4$test_df.pred.rtree_4))
result_df4 <- aggregate(. ~ fullVisitorId, result_df4, sum)
RMSE(log1p(result_df4$transactionRevenue), log1p(result_df4$predictedRevenue))
```

```{r}
# decision tree plot
fancyRpartPlot(rt_4)
```


```{r}
#decision tree implementation on split train data
rt5 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            totals.sessionQualityDim, data=train)

#applying the trained model on split test data
test.pred.rtree5 <- predict(rt5,test)
RMSE.rtree5 <- sqrt(mean((test.pred.rtree5-test$logRevenue)^2))
RMSE.rtree5


#decision tree implementation on actual train data 
rt_5 <- rpart(logRevenue ~ totals.pageviews +
            totals.hits +
            totals.sessionQualityDim, data=train_df)

#applying the trained model on actual test data
test_df.pred.rtree_5 <- predict(rt_5,test_df)
p5 <- as.data.frame(test_df.pred.rtree_5)
result_df5 <- data.frame(fullVisitorId=test_df$fullVisitorId, transactionRevenue=test_df$totals.totalTransactionRevenue, predictedRevenue=expm1(p5$test_df.pred.rtree_5))
result_df5 <- aggregate(. ~ fullVisitorId, result_df5, sum)
RMSE(log1p(result_df5$transactionRevenue), log1p(result_df5$predictedRevenue))
```

```{r}
# decision tree plot
fancyRpartPlot(rt_5)
```


